# AI/ML Task 2: Feature Engineering, Model Optimization & Performance Comparison

This project improves the basic house price prediction workflow by adding CSV loading, preprocessing, feature engineering, feature scaling, multiple regression models, and model performance comparison.

## Files

- `Task2_Model_Comparison.ipynb` - Executed notebook with results.
- `AI_ML_Task2_Model_Comparison.ipynb` - Notebook template/workflow file.
- `AI_ML_Task2_Model_Comparison_Report.pdf` - PDF report based on the executed notebook results.
- `task2_best_house_price_model.pkl` - Saved best model, generated by the notebook.

## Dataset

The executed notebook used the California Housing dataset uploaded as `housing.csv`.

Dataset summary:

- Rows: 20,640
- Columns after preprocessing: 13
- Features after engineering: 14
- Training rows: 16,512
- Testing rows: 4,128

Target variable:

- `HousePrice`

Input features include:

- Median income
- House age
- Average rooms
- Average bedrooms
- Population
- Average occupancy
- Latitude
- Longitude

Additional engineered features:

- `RoomsPerPerson`
- `BedroomRatio`

## Models Compared

- Linear Regression
- Ridge Regression
- Decision Tree Regressor
- Random Forest Regressor

## Evaluation Metrics

The models are compared using:

- MAE
- RMSE
- R2 Score

Lower MAE/RMSE is better. Higher R2 Score is better.

## Model Comparison Results

| Model | MAE | RMSE | R2 Score |
|---|---:|---:|---:|
| Random Forest | 0.339168 | 0.515623 | 0.797111 |
| Linear Regression | 0.482436 | 0.673856 | 0.653481 |
| Ridge Regression | 0.482428 | 0.673860 | 0.653477 |
| Decision Tree | 0.496911 | 0.712963 | 0.612094 |

## Best Model

The best-performing model was **Random Forest**, selected because it had the lowest RMSE and highest R2 Score.

Cross-validation for the best model:

- Mean CV R2: 0.600494
- Std CV R2: 0.124293

## How to Run

1. Open `Task2_Model_Comparison.ipynb` or `AI_ML_Task2_Model_Comparison.ipynb` in Google Colab or Jupyter Notebook.
2. Run all cells from top to bottom.
3. Upload `housing.csv` when prompted, or let the notebook use the scikit-learn fallback.
4. Review the model comparison table.
5. Check the actual vs predicted and residual plots.
6. The best model is saved as `task2_best_house_price_model.pkl`.

## Conclusion

Task 2 shows how ML workflows improve beyond a basic model. The notebook compares multiple algorithms, uses feature engineering and scaling, evaluates performance using regression metrics, and selects Random Forest as the best model based on RMSE and R2 Score.
